### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by arashbahreini** [arashbahreini/practice-react#2]
The project will be a university which contains several menus, each menu opens in a different page

- [ ] Add routing to the project
- [x] Design menus with click events to change the url ( classes, teachers, students, departments )
- [ ] Add Bootstrap and style the menus
- [ ] Generate and design components for each menu
